LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := i2cdetect
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := i2cdetect 
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := i2cget
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := i2cget
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := i2cset
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := i2cset 
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := i2cdump
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := i2cdump 
include $(BUILD_PREBUILT)
